SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Terminals](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TerminalGuid] [uniqueidentifier] NOT NULL,
	[TerminalCode] [varchar](20) NOT NULL,
	[TerminalName] [varchar](100) NOT NULL,
	[BranchId] [int] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[MacAddress] [nvarchar](12) NULL,
PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Terminals] ADD UNIQUE NONCLUSTERED
(
	[TerminalGuid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



ALTER TABLE [dbo].[Terminals] ADD  CONSTRAINT [UQ_Terminals_TerminalCode] UNIQUE NONCLUSTERED
(
	[TerminalCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Terminals] ADD  DEFAULT ((1)) FOR [IsActive]
GO

ALTER TABLE [dbo].[Terminals] ADD  DEFAULT (getdate()) FOR [CreatedDate]
GO

ALTER TABLE [dbo].[Terminals] WITH CHECK ADD CONSTRAINT FK_Terminals_Branches FOREIGN KEY(BranchId) REFERENCES dbo.Branches(Id);
GO
