CREATE TABLE Terminals
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    TerminalGuid UNIQUEIDENTIFIER NOT NULL UNIQUE,
    TerminalCode VARCHAR(20) NOT NULL UNIQUE,
    TerminalName VARCHAR(100) NOT NULL,
    BranchId INT NOT NULL,
    IsActive BIT NOT NULL DEFAULT(1),
    CreatedDate DATETIME NOT NULL DEFAULT(GETDATE())
);